### ISSUE TITLE
[Bug] ImportError in Fabric

### ISSUE THREAD

**Issue by sudo-Tiz** [rubiin/HyDePanel#124]
## Description
Running main.py results in an ImportError:

## Error
ImportError: cannot import name 'HyprlandLanguage' from 'fabric.hyprland.widgets'
This is caused by Commit 353cb3f, which changed the import statement.

## Fix
To resolve this issue, I removed the .venv directory and reran init.sh -setup.
However, there is an issue with the -setup option, and the init script needs to be modified 

### Reproduction

init.sh -setup

### System Info

```Shell
NA
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/rubiin/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/rubiin/.github/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rubiin** [comment]
Thats cause the new fabric version has modified the `Language` to `HyprlandLanguage`. If you can suggest the changes, maybe we can add it
